# platform :ios, '9.0'

target 'GCWebContainerDemo' do
  use_frameworks!
  pod 'Zip', '~> 2.1'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Tiercel'
  pod 'GCWebContainer', :path=>'../../GCWebContainer'
  pod 'Pandora', :path=>'../../Pandora/ios'
  pod 'BrowserKit', :path=>'../../BrowserKit'
end
