# platform :ios, '9.0'

target 'GCWebContainerDemo' do
  use_frameworks!
  pod 'Zip', '~> 2.1'
  pod 'SnapKit', '~> 5.0.0'
  pod 'Tiercel'
  pod 'GCWebContainer', '~> 0.1.5'
  pod 'Pandora', '~> 0.1.0'
  pod 'BrowserKit', '~> 0.1.0'
end
